### ISSUE TITLE
Пагинация данных

### ISSUE THREAD

**Issue by tmcgroul** [donkey-engine/donkey-engine-ui#12]
Сейчас в репозитории бэкенда почти все эндпоинты отдают пагинированные данные, с этим не очень удобно работать.

Варианты:
1. Нужно либо придумывать вспомогательные функции, которые будут через while do грузить все страницы с данными.
2. Обсудить как пагинация должна отразиться на пользовательском интерфейсе.
3. Убрать дефолтную пагинацию до востребованности.

**Comment by tmcgroul** [comment]
@BehindLoader я бы пока убрал её, мне кажется, что она сейчас не очень нужна, на клиенте, у нас вроде не планируется столько данных...
Можно впрынципе вызовы апи в сервисный слой вынести и там все эти неприятные моменты обрабатывать (1 вариант)

**Comment by ya7on** [comment]
@tmcgroul Можно и убрать вообще. Я не против. Она и правда не нужна пока что
Но это пока что
Но потом, если ее придется возвращать, не придется ли перелопатить все взаимодействие с апи (пол проекта)?

**Comment by tmcgroul** [comment]
А потом мы будем добавлять пагинацию точечно - если есть какая-то сущность, которую нужно загружать чанками, то добавим к вьюхе всё необходимое. Навряд ли понадобится добавлять пагинацию сразу для всех ресурсов.
И нужно всё-таки сгруппировать вызовы апи в одном месте. Тогда если для какого-то ресурса добавится пагинация, то для начала можно будет обойтись изменениями в модуле с вызовом апи, а потом уже переделывать интерфейс под работу с пагинацией.

**Comment by ya7on** [comment]
Согласен. Давай так и сделаем
