### ISSUE TITLE
Страница подтверждения аккаунта

### ISSUE THREAD

**Issue by ya7on** [donkey-engine/donkey-engine-ui#13]
Здесь сделана апишка для подтверждения эмейла
donkey-engine/donkey-engine#60 

Нужно еще задумать об ограничении для неподтвержденных пользователей. Например не давать им создавать сервера
С фронта нужно окошко

**Comment by tmcgroul** [comment]
@BehindLoader можно сделать чтобы создавались неактивные пользователи, которые не могут аутентифицироваться в приложении, потом им приходит ссылка на почку, при переходе по которой у них активируется профиль и можно после этого атоматически логинить в приложение или просто редиректить на логин
автоматически это хорошо, но если заставить пользователя ввести креденшелсы, то меньше вероятность, что он их забудет

**Comment by ya7on** [comment]
@tmcgroul Я не представляю как это реализовать. У нас подтверждение использует авторизованного пользователя. Инстанс пользователя нужен для проверки кода подтверждения

**Comment by tmcgroul** [comment]
> У нас подтверждение использует авторизованного пользователя.

так подправить же можно...

**Comment by ya7on** [comment]
@tmcgroul Ну вообще можно да
Принимать еще `username` и `password` в эндпоинте подтверждения эмейла

**Comment by tmcgroul** [comment]
> @tmcgroul Ну вообще можно да
> Принимать еще `username` и `password` в эндпоинте подтверждения эмейла

так у пользователя есть токен, который он при переходе по ссылке в почте отправит на сервак
username и password тут не нужен

**Comment by ya7on** [comment]
@tmcgroul Та не хочется просто передылавать токены. В Джанго есть встроеные, но они принимают инстанс пользователя

**Comment by tmcgroul** [comment]
так ничего не надо переделывать
предложу всё-таки убрать email_confirmed из профиля, потому что пользователь без подтверждения почты вообще не должен иметь возможность пройти аутентификацию

**Comment by tmcgroul** [comment]
> @tmcgroul Та не хочется просто передылавать токены. В Джанго есть встроеные, но они принимают инстанс пользователя

так инстанс будет, просто он будет неактивен до тех пор, пока юзер не подвердит свою почту

**Comment by tmcgroul** [comment]
хочю сделать мр и показать как я всё это вижу, но нужно решить с email_confirmed, я не вижу у этого предназначения
впускать юзера в приложения без возможности сделать шо-то => это только усложнит фронтенд всякими условиями

**Comment by ya7on** [comment]
Ок. Сделай как нужно

**Comment by tmcgroul** [comment]
@BehindLoader а нужна страница чтобы показывать что успешно подтверждено или достаточно редиректа на логин пейдж?

**Comment by ya7on** [comment]
Можно и просто редиректить
