### ISSUE TITLE
Баг с истечением сессии

### ISSUE THREAD

**Issue by tmcgroul** [donkey-engine/donkey-engine-ui#17]
Время сессии может истечь, но в приложении это никак не обрабатывается

**Comment by ya7on** [comment]
Для подключения премиум и подтверждения эмейла нужно сделать эндпоинт `/me` по которому будет выводиться актуальная инфа о пользователе при загрузке страницы. Можно через этот эндпоинт проверять авторизован ли пользователь
Как идея?

**Comment by ya7on** [comment]
Вот МР donkey-engine/donkey-engine#75

**Comment by tmcgroul** [comment]
я пажилой эндпоинт а хто?
думою это надо на уровне эйчтитипи клиента проверять каждый респонс, шо-то типа мидлвару добавить, если сервер возвращает 401 unathorized то проводить махинации с очисткой локалСтоража и редиректить на /signin
