### ISSUE TITLE
Изменение названия сервера

### ISSUE THREAD

**Issue by ya7on** [donkey-engine/donkey-engine-ui#26]

**Comment by ya7on** [comment]
И добавить инпут с названием сервера в модалку "Создать Сервер"

**Comment by tmcgroul** [comment]
@BehindLoader nu vot est' u nas route dlya stranici servera - `/server/<id>`, a chto delat' esli vvesti nesuwestvuyuwiy server?
mojno redirectit' na dashboard ili pokazivat' not found
ya bi prosto redirectil...

**Comment by ya7on** [comment]
@tmcgroul Я бы тоже. Давай просто редиректить. Потом 404 страницу сделаем
